### ISSUE TITLE
Pass the user language to the Q&A service.

### ISSUE THREAD

**Issue by dmorand** [dialoguemd/covidflow#39]
While the Q&A service has language detection features, we should still explicitly pass the language when querying it. To do so, the user language must be available in the action server request using a slot which means that the core servers must be aware of their language.

To do so, we should add a `language` slot to the domain file and initialize it with the proper language:

```
slots:
  language:
    type: unfeaturized
    initial_value: en
```

The value could either be specified in separate `domain.$language.yml` or using an environment variable if possible.
